package com.csme.assist.leave.notification.entity;

public enum NotificationEvent {


    LEAVE_CREATION_APPROVER,LEAVE_CREATION_SEEKER,LEAVE_MODIFICATION,LEAVE_REJECTION_APPROVER,LEAVE_REJECTION_SEEKER,LEAVE_APPROVAL_APPROVER,LEAVE_APPROVAL_SEEKER,LEAVE_DELETION

}
