apiVersion: v1
kind: Service
metadata:
  name: {{ include "edi-claim-prepay-api.serviceName" . }}
  labels:
    {{- include "edi-claim-prepay-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "edi-claim-prepay-api.selectorLabels" . | nindent 4 }}
