package com.finstack.assist.leave.notification.entity;

public enum NotificationEvent {


    LEAVE_CREATION_APPROVER,LEAVE_CREATION_SEEKER,
    LEAVE_MODIFICATION_APPROVER,LEAVE_MODIFICATION_SEEKER,
    LEAVE_REJECTION_APPROVER,LEAVE_REJECTION_SEEKER,
    LEAVE_APPROVAL_APPROVER,LEAVE_APPROVAL_SEEKER,
    LEAVE_DELETION_APPROVER,LEAVE_DELETION_SEEKER

}
